dist: xenial

language: python
python:
  - {{ cookiecutter.python_version }}

node_js: '8'

install:
  - pip install -U tox-travis
  - pip install python-coveralls
  - npm install commitlint-travis
script:
  - node_modules/.bin/commitlint-travis
  - tox -r
after_success:
  - coveralls

notifications:
  email: false
